// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvs4u6YRyKQEhTeAITvmMjFZl7DnPg_oU',
    appId: '1:839487780320:web:3da0e4c01c1637788c6785',
    messagingSenderId: '839487780320',
    projectId: 'hello-app-8610b',
    authDomain: 'hello-app-8610b.firebaseapp.com',
    databaseURL: 'https://hello-app-8610b-default-rtdb.firebaseio.com',
    storageBucket: 'hello-app-8610b.firebasestorage.app',
    measurementId: 'G-K1X56JLENV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTt8pApZ6dEEmczYrXXOBAc-VNYL_oAaU',
    appId: '1:839487780320:android:6bfd3403f491362d8c6785',
    messagingSenderId: '839487780320',
    projectId: 'hello-app-8610b',
    databaseURL: 'https://hello-app-8610b-default-rtdb.firebaseio.com',
    storageBucket: 'hello-app-8610b.firebasestorage.app',
  );
}
